### ISSUE TITLE
Error performing WebflowSync::CreateItemJob -> NameError (uninitialized constant WebflowSync::Api):

### ISSUE THREAD

**Issue by aedificator-nl** [vfonic/webflow_sync#54]
Hi,

I am trying to get `webflow_sync` working, however I get a `NameError` for `WebflowSync::Api` when the `CreateItemJob` is run from Sidekiq. 

If I run the job from the Rails console I get the same error. If I then type `WebflowSync::API` I get a `Zeitwerk::NameError` as the `api.rb` does not contain a class named `API` (logically). This however does result in `Api` being loaded and attempting the `CreateItemJob` again now works.

I am not sure why the Rails autoloader is not picking up the file correctly, so unfortunately don't have a suggested solution.

Kind regards,

Steven

**Comment by aedificator-nl** [comment]
Found the probable cause, we have 

```
  inflect.acronym "API"
```

in our `inflections.rb`.

Closing the issue as this seems to be a problem on our end.

**Comment by vfonic** [comment]
Interesting find nevertheless!

What do you think if we'd do something like: 
`WebflowSync::API = WebflowSync::Api` at the bottom of `api.rb`?
Would that make sense and prevent such future issues?

It feels to me like it goes well with Ruby's/Rails' mentality of being able to do the same thing in five different ways.
A good example would be collection methods: https://github.com/rubocop/ruby-style-guide#map-find-select-reduce-include-size

**Comment by aedificator-nl** [comment]
Thanks!

Not sure, I think the general opinion is that inflections should be used sparsely, and never in such a general way as was done on our project. I have decided to strip out the inflections and use standard Rails class naming, so `Api` instead of `API`.  For us such a change won't be necessary.

In general I am not sure how happy Zeitwerk would be with 2 classes being defined in a single file, my feeling is that this goes against the intended architecture as well.
