### ISSUE TITLE
InitialSyncJob always uses `find_collection_id` from API instead of calling `webflow_collection_id` on model

### ISSUE THREAD

**Issue by aedificator-nl** [vfonic/webflow_sync#55]
The InitialSyncJob always uses the `find_collection_id` API method (`initial_sync_job.rb:10`) instead of calling `webflow_collection_id` on the appropriate model. 

It would be nice if the `InitialSyncJob` would call the model for the `webflow_collection_id`, so any overwrite can be used, for example when the `collection_id` is set directly, without using the `slug`.

I wanted to create a PR for this, couldn't get the `bundle` working as I had errors with making `nio4r`. Will create a PR once fixed, but for now adding an issue as well.

**Comment by vfonic** [comment]
Good catch! I just "recently" added `webflow_collection_id` method on models and I didn't use `InitialSyncJob` and missed to make a call there.

Looking forward to your PR!
